### ISSUE TITLE
docs: update package version to v0.2.9

### ISSUE THREAD

**Issue by amatria** [HAN-Siyu/LION#2]
The README is outdated with respect to the current LION version:
https://github.com/HAN-Siyu/LION/blob/4ab5870550b3162174f723d485b9111ea4812ffd/README.md?plain=1#L21

**Comment by amatria** [comment]
Also, what does it mean that the `evaluate_performance()` function has been fixed? Did it produce wrong accuracies, etc.? Does it mean that the results in the paper are better?

**Comment by HAN-Siyu** [comment]
> Also, what does it mean that the `evaluate_performance()` function has been fixed? Did it produce wrong accuracies, etc.? Does it mean that the results in the paper are better?

Hi @amatria,

Thanks for the interest. The original `evaluate_performance()` was specifically designed for the experiments in our study, and we used labels such as "Interact" and "Non-interact" to denote positive and negative classes. And `evaluate_performance()` always assumes the positive class is before the negative class in the confusion table. This could sometimes mistake positive class as negative class (for example, use labels 1 and 0 to denote positive and negative classes), so the metrics such as sensitivity, precision, etc will not be correct in this case. We fixed this issue in the latest version. Fortunately, this will not affect the results in the paper.

Sorry for the inconvenience, please let me know if you have further questions.

Best,
Siyu

**Comment by HAN-Siyu** [comment]
> The README is outdated with respect to the current LION version:
> 
> https://github.com/HAN-Siyu/LION/blob/4ab5870550b3162174f723d485b9111ea4812ffd/README.md?plain=1#L21

And thank you for pointing this out. Will fix it later when I'm able to access all the source data.

**Comment by amatria** [comment]
Hi @HAN-Siyu 

I appreciate the careful response :)

Thank you very much

**Comment by HAN-Siyu** [comment]
> Hi @HAN-Siyu
> 
> I appreciate the careful response :)
> 
> Thank you very much

Hi @amatria 

Just updated links for v0.2.9. Thank you again for helping fix the issue!

**Comment by HAN-Siyu** [comment]
Hi @amatria,

LION has just been updated to v.0.2.9.1. The code in v0.2.9 has the same issue (mentioned above) when retraining the model of LION (using `run_LION()`). Please kindly use the latest version and check the LION's output if you used labels such as 0 and 1 to denote negative and positive classes. Sorry for the issue and the inaccurate results produced by LION.

Best regards,
Siyu
